name: gh_action_publish
description: gh_action_publish
version: 0.0.1+3
repository: https://github.com/chan150/gh_action_publish

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
#  copy_with_extension: ^5.0.2
#  equatable : ^2.0.5
#  fl_chart: ^0.62.0
  flutter:
    sdk: flutter

dev_dependencies:
#  build_runner: ^2.4.4
#  copy_with_extension_gen: ^5.0.2
  flutter_test:
    sdk: flutter
#  mocktail: ^0.3.0
#  very_good_analysis: ^5.0.0+1
