name: Publish to pub.dev

on:
  push:
    branches: [ "pub" ]
  pull_request:
    branches: [ "pub" ]

permissions:
  id-token: write # This is required for authentication using OIDC
  contents: read # default

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          cache: true
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # C:\Users\ccc\AppData\Roaming\dart\pub-credentials.json
      - name: pub-credentials.json
        env:
          LOGIN: ${{ secrets.LOGIN }}
        run: |
          mkdir -p $HOME/.config/dart
          echo "$LOGIN" > $HOME/.config/dart/pub-credentials.json
#          cat $HOME/.config/dart/pub-credentials.json

      - name: Install dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        run: flutter pub publish -f

