name: Publish to pub.dev

#on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+*'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#jobs:
#  build:
#    runs-on: ubuntu-latest
#  steps:
#    - uses: actions/checkout@v3
#    - uses: subosito/flutter-action@v2
#      with:
#        channel: 'stable'
#    - run: flutter --version
#    - name: Install dependencies
#      run: flutter pub get

permissions:
  id-token: write # This is required for authentication using OIDC
  contents: read # default

#jobs:
#  publish:
#    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          cache: true
#      #      - uses: dart-lang/setup-dart@v1
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#          cache: true

#      - name: pub credentials json
#          env:
#            SUPER_SECRET: ${{ secrets.SuperSecret }}
#          run: |
#            echo "$SUPER_SECRET"
      - name: echo SuperSecret
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo "$SuperSecret"
#      - name: Install dependencies
#        run: flutter pub get
#      - name: Publish
#        run: flutter pub publish -f

